FROM golang:1.23.1-alpine3.20

WORKDIR /app

RUN go install github.com/air-verse/air@latest && \
    go install github.com/a-h/templ/cmd/templ@latest

COPY go.mod go.sum ./

RUN go mod download

CMD [ "air", "-c", ".air-with-proxy.toml" ]
