name: pre-commit

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.1'

    - uses: actions/setup-python@v3

    - uses: pre-commit/action@v3.0.1
